# Generated by Django 3.1.2 on 2020-10-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donatorName', models.CharField(max_length=100)),
                ('donatorMobile', models.CharField(max_length=100)),
                ('donationAddress', models.TextField()),
                ('landMark', models.CharField(max_length=100)),
                ('foodType', models.CharField(max_length=100)),
                ('foodName', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('pickupDate', models.CharField(max_length=100)),
                ('preferedTime', models.CharField(max_length=100)),
                ('foodDescription', models.TextField()),
                ('latitude', models.FloatField()),
                ('longititude', models.FloatField()),
            ],
        ),
    ]
