# Generated by Django 3.1.2 on 2020-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_cloths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donatorName', models.CharField(max_length=100)),
                ('donatorMobile', models.CharField(max_length=100)),
                ('donationAddress', models.TextField()),
                ('landMark', models.CharField(max_length=100)),
                ('booksType', models.CharField(max_length=100)),
                ('booksName', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('pickupDate', models.CharField(max_length=100)),
                ('preferedTime', models.CharField(max_length=100)),
                ('booksDescription', models.TextField()),
                ('latitude', models.FloatField()),
                ('longititude', models.FloatField()),
            ],
        ),
    ]
